default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: angularlist_development

test: &test
  <<: *default
  database: angularlist_test


production:
  <<: *default
  database: angularlist_production
  username: angularlist
  password: <%= ENV['ANGULARLIST_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test